version: '3.9'

#networks:
#  default:
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.169.0/24

#x-logging:
#  &default-logging
#  driver: fluentd
#  options:
#    fluentd-address: localhost:24224
#    fluentd-max-retries: 10
#    tag: "/aws/ecs/{{.Name}}"


services:
  localstack:
    image: "${LOCALSTACK_IMAGE:-localstack/localstack:latest}"
    restart: always
    environment:
      - LOCALSTACK_HOST=localhost:$LOCALSTACK_PORT
      - GATEWAY_LISTEN=0.0.0.0:$LOCALSTACK_PORT
      - DYNAMODB_SHARE_DB=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /var/lib/localstack:exec,mode=600
    ports:
      - "${LOCALSTACK_PORT}:${LOCALSTACK_PORT}" # edge service
    healthcheck:
      test: awslocal s3 ls && awslocal secretsmanager list-secrets
      interval: 3s
      timeout: 10s
