- name: set aws_facts fact
  set_fact:
    aws_region: "{{ aws_region }}"
    aws_cmd: "aws --region={{ aws_region }}"

- name: get aws account_id
  command: "{{ aws_cmd }} sts get-caller-identity --query Account --output text"
  register: account_id
  changed_when: false
  check_mode: false

- name: get patch version
  command: "poetry version patch --dry-run -s"
  register: next_version
  changed_when: false
  check_mode: false

- name: get head hash
  command: "git rev-parse --short HEAD"
  register: head_revision
  changed_when: false
  check_mode: false

# - name: timestamp seconds
#  shell: |
#    set -o pipefail
#    date -u -Iseconds | head -c 19 | sed -e 's#[-T\\:]*##g'"
#  register: timestamp
#  changed_when: false
#  check_mode: false

- name: set aws_facts fact
  set_fact:
    aws_account_id: "{{ account_id.stdout }}"
    ecr_registry: "{{ account_id.stdout }}.dkr.ecr.eu-west-2.amazonaws.com"
    docker_build_label: "pre{{ next_version.stdout }}-sha{{ head_revision.stdout }}"
