name: "common-build-steps"
description: "regular build steps"


runs:
  using: "composite"
  steps:

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: print branch info
      shell: bash
      run: |
        git branch
        echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
        echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
        git log --oneline -n 10

    - name: clean
      shell: bash
      run: |
        git clean -fdx

    - name: check secrets
      uses: ./.github/actions/check-secrets

    - name: merge into base_branch
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.number }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        echo base branch "${GITHUB_BASE_REF}"
        echo pr branch "${GITHUB_HEAD_REF}"
        git checkout "${GITHUB_BASE_REF}"
        git checkout -b "merging-${PR_NUMBER}"
        git merge --ff-only "${PR_HEAD_SHA}"

    - name: git reset
      shell: bash
      run: git reset --hard


    - name: replace remove some unneeded tools
      if: ${{ hashFiles('mise.toml', '!.venv/**') }}
      shell: bash
      run: |
        sed -E 's/^python /#python /' -i mise.toml
        sed -E 's/^pre-commit /#pre-commit /' -i mise.toml

    - name: Install tools from mise config
      if: ${{ hashFiles('mise.toml', '!.venv/**') }}
      uses: ./.github/actions/mise-cache

    - name: cache virtualenv
      uses: actions/cache@v4
      with:
        path: |
          .venv
          **/.lock-hash
          **/requirements.txt
        key: ${{ runner.os }}-py-${{ inputs.python-version }}-uv-${{ hashFiles('./uv.lock', '!.venv/**') }}

    - name: install
      shell: bash
      run: make install-ci
