apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - .rendered.helm.yaml

images:
  - name: docker.io/grafana/alloy
    newName: "${docker_registry}/grafana/alloy"
    newTag: "v1.7.4"
  - name: registry.k8s.io/kube-state-metrics/kube-state-metrics
    newName: "${docker_registry}/kube-state-metrics/kube-state-metrics"
    newTag: "v2.15.0"
  - name: quay.io/prometheus/node-exporter
    newName: "${docker_registry}/prometheus/node-exporter"
    newTag: "v1.9.0"
  - name: ghcr.io/jimmidyson/configmap-reload
    newName: "${docker_registry}/jimmidyson/configmap-reload"
    newTag: "v0.14.0"
