name: odin-merge
on:
  push:
    branches:
      - develop

jobs:

  scan:
    runs-on: ubuntu-latest

    steps:

      - name: checkout the calling repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: build-common
        uses: ./.github/actions/build-common

      - name: run tests
        shell: bash
        run: |
          make coverage-ci

      - name: convert sonar reports
        if: ${{ hashFiles('./reports/junit/*.xml', '!.venv/**') || hashFiles('./reports/coverage.xml', '!.venv/**') }}
        uses: ./.github/actions/sonar-reports

      - name: prepare sonar properties
        if: ${{ hashFiles('./sonar-project.properties', '!.venv/**') }}
        uses: ./.github/actions/sonar-properties

      - name: sonarqube scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  tag-version:
    runs-on: ubuntu-latest

    timeout-minutes: 30
    steps:
      - name: checkout the calling repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: get uv version
        id: uv-version
        shell: bash
        run: |
          if grep -Eq "^uv .*" mise.toml 2> /dev/null; then
            version="$(grep -oP '^uv = "\K\d+\.\d+\.\d+' mise.toml)"
          else
            version="0.11.28"
          fi
          echo "version=${version}"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: install mise / uv
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c  # 4.3.0
        with:
          install: true
          cache: true
          tool_versions: |
            uv ${{ steps.uv-version.outputs.version }}
          reshim: true
          github_token: ${{ inputs.github-token }}

      - name: uv get release version
        shell: bash
        id: get-version
        run: |
          VERSION="v$(uvx --no-build hatch@1.17.1 version | sed -E 's#rc.*$##')"
          echo "VERSION=${VERSION}"
          if [ -z "${VERSION}" ]; then
          exit 1
          fi
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: increment patch version and replace major version
        shell: bash
        run: |
          # Create semantic version tag: vN.N.N
          SEMANTIC_VERSION="${{ steps.get-version.outputs.version }}"
          git tag "${SEMANTIC_VERSION}"
          git push origin "${SEMANTIC_VERSION}"

          # Delete existing major version tag if it already exists: vN
          MAJOR_VERSION="$(echo ${SEMANTIC_VERSION} | cut -d. -f1)"
          if [[ $(git tag --list ${MAJOR_VERSION}) != "" ]]; then
            git tag -d ${MAJOR_VERSION}
            git push origin :refs/tags/${MAJOR_VERSION}
          fi

          # Create major version tag
          git tag "${MAJOR_VERSION}"
          git push origin "${MAJOR_VERSION}"
