name: pull-request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:

  lint:
    uses: NHSDigital/odin-actions/.github/workflows/standard-linting.yml@v1

  test:
    uses: NHSDigital/odin-actions/.github/workflows/test-and-sonar-scan.yml@v1
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

#  validate-build:
#
#    runs-on:
#      - codebuild-runner-terraform-aws-metrics-lambda-${{ github.run_id }}-${{ github.run_attempt }}
#      - buildspec-override:true
#    steps:
#
#      - name: checkout the calling repo
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - name: common build setup
#        uses: NHSDigital/odin-actions/.github/actions/build-common@v1
#
#      - name: build artifacts
#        id: build-artifacts
#        uses: NHSDigital/odin-actions/.github/actions/build-artifacts@v1
#        with:
#          application: "metriczzz"
#
##      - name: terraform-plan
##        uses: NHSDigital/odin-actions/.github/actions/terraform-stack-plan-no-lock-codepipeline@v1
##        with:
##          application: "metriczzz"
##          version: ${{ steps.build-artifacts.outputs.version }}

  auto-merge-dependabot:
    needs:
      - lint
      - test
#      - validate-build
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    uses: NHSDigital/odin-actions/.github/workflows/dependabot-automation.yml@v1
    with:
      repo-name: "${{ github.repository }}"
      auto-approve: true
      auto-merge: true
